# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1908, 932)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-90, 0, 2081, 961))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("GUI matrials/Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 10, 681, 431))
        self.bg_2.setStyleSheet("background-color: rgb(0, 245, 245);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(710, 10, 741, 431))
        self.bg_3.setStyleSheet("background-color: rgb(0, 245, 245);")
        self.bg_3.setText("")
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(20, 20, 661, 411))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("GUI matrials/Iron_Template_9.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(720, 20, 721, 411))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("GUI matrials/live.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(-70, 410, 761, 521))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("GUI matrials/Ntuks.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(1470, 10, 431, 221))
        self.bg_4.setStyleSheet("background-color: rgb(0, 245, 245);")
        self.bg_4.setText("")
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(1480, 20, 411, 201))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("GUI matrials/Earth_Template.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Test_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Test_Time.setGeometry(QtCore.QRect(1420, 770, 461, 141))
        self.Test_Time.setStyleSheet("background-color: Transparent;\n"
"border -radius:none;\n"
"color: rgb(0, 255, 255);")
        self.Test_Time.setObjectName("Test_Time")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(1420, 770, 471, 141))
        self.bg_5.setStyleSheet("border -raduis:none;\n"
"color: rgb(0, 255, 255);")
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap("GUI matrials/gyhf.jpg"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        self.Test_Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Test_Day.setGeometry(QtCore.QRect(1430, 620, 461, 141))
        self.Test_Day.setStyleSheet("background-color: Transparent;\n"
"border -radius:none;\n"
"color: rgb(0, 255, 255);")
        self.Test_Day.setObjectName("Test_Day")
        self.Test_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Test_Date.setGeometry(QtCore.QRect(1430, 460, 461, 141))
        self.Test_Date.setStyleSheet("background-color: Transparent;\n"
"border -radius:none;\n"
"color: rgb(0, 255, 255);")
        self.Test_Date.setObjectName("Test_Date")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(1420, 620, 471, 141))
        self.bg_6.setStyleSheet("border -raduis:none;\n"
"color: rgb(0, 255, 255);")
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("GUI matrials/gyhf.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(1420, 460, 471, 141))
        self.bg_7.setStyleSheet("border -raduis:none;\n"
"color: rgb(0, 255, 255);")
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("GUI matrials/gyhf.jpg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1480, 250, 411, 81))
        self.pushButton_start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(0, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.bg_8.setGeometry(QtCore.QRect(1470, 240, 431, 201))
        self.bg_8.setStyleSheet("background-color: rgb(0, 245, 245);")
        self.bg_8.setText("")
        self.bg_8.setScaledContents(True)
        self.bg_8.setObjectName("bg_8")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(1480, 350, 411, 81))
        self.pushButton_exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(0, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_youtube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_youtube.setGeometry(QtCore.QRect(710, 460, 301, 91))
        self.pushButton_youtube.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton_youtube.setObjectName("pushButton_youtube")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(710, 620, 301, 91))
        self.pushButton_whatsapp.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(1070, 460, 301, 91))
        self.pushButton_chrome.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.bg_1.raise_()
        self.Gif_3.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.Gif_1.raise_()
        self.Gif_2.raise_()
        self.bg_4.raise_()
        self.Gif_4.raise_()
        self.Test_Time.raise_()
        self.bg_5.raise_()
        self.Test_Day.raise_()
        self.Test_Date.raise_()
        self.bg_6.raise_()
        self.bg_7.raise_()
        self.bg_8.raise_()
        self.pushButton_start.raise_()
        self.pushButton_exit.raise_()
        self.pushButton_youtube.raise_()
        self.pushButton_whatsapp.raise_()
        self.pushButton_chrome.raise_()
        JarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.pushButton_start.setText(_translate("JarvisUi", "START"))
        self.pushButton_exit.setText(_translate("JarvisUi", "EXIT"))
        self.pushButton_youtube.setText(_translate("JarvisUi", "YOUTUBE"))
        self.pushButton_whatsapp.setText(_translate("JarvisUi", "WHATSAPP"))
        self.pushButton_chrome.setText(_translate("JarvisUi", "CHROME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
